---

Organizations:
  - &Org3
    Name: Org3MSP
    ID: Org3MSP
    MSPDir: ../organizations/peerOrganizations/org3.dt4h.com/mspConfig
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org3MSP.admin','Org3MSP.client','Org3MSP.peer')"
      Writers:
        Type: Signature
        Rule: "OR('Org3MSP.admin','Org3MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org3MSP.peer')"

    AnchorPeers:
      - Host: peer0.org3.dt4h.com
        Port: 10070
