General:
  ListenAddress: 0.0.0.0
  ListenPort: 9051
  TLS:
    Enabled: true
    PrivateKey: /var/hyperledger/orderer/tls/keystore/key.pem
    Certificate: /var/hyperledger/orderer/tls/signcerts/cert.pem
    RootCAs:
      - /var/hyperledger/orderer/tls/tlscacerts/ca.crt
    ClientAuthRequired: false
    ClientRootCAs: /var/hyperledger/orderer/tls/tlscacerts/ca.crt
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  Cluster:
    SendBufferSize: 10
    ClientCertificate: /var/hyperledger/orderer/tls/signcerts/cert.pem
    ClientPrivateKey: /var/hyperledger/orderer/tls/keystore/key.pem
    ListenPort: 9052
    ListenAddress: 0.0.0.0
    ServerCertificate: /var/hyperledger/orderer/tls/signcerts/cert.pem
    ServerPrivateKey: /var/hyperledger/orderer/tls/keystore/key.pem
    RootCAs:
      - /var/hyperledger/orderer/tls/tlscacerts/ca.crt
  BootstrapMethod: file
  BootstrapFile: /var/hyperledger/orderer/genesis.block
  LocalMSPDir: /var/hyperledger/orderer/msp
  LocalMSPID: TexordererMSP
  Profile:
    Enabled: false
    Address: '0.0.0.0:6060'
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore: null
    PKCS11:
      Library: null
      Label: null
      Pin: null
      Hash: null
      Security: null
      FileKeyStore:
        KeyStore: null
  Authentication:
    TimeWindow: 15m
FileLedger:
  Location: /var/hyperledger/production/orderer
  Prefix: hyperledger-fabric-ordererledger
Kafka:
  Retry:
    ShortInterval: 5s
    ShortTotal: 10m
    LongInterval: 5m
    LongTotal: 12h
    NetworkTimeouts:
      DialTimeout: 10s
      ReadTimeout: 10s
      WriteTimeout: 10s
    Metadata:
      RetryBackoff: 250ms
      RetryMax: 3
    Producer:
      RetryBackoff: 100ms
      RetryMax: 3
    Consumer:
      RetryBackoff: 2s
  Topic:
    ReplicationFactor: 3
  Verbose: false
  TLS:
    Enabled: false
    PrivateKey: null
    Certificate: null
    RootCAs: null
  SASLPlain:
    Enabled: false
    User: null
    Password: null
  Version: null
Debug:
  BroadcastTraceDir: null
  DeliverTraceDir: null
Operations:
  ListenAddress: '127.0.0.1:8447'
  TLS:
    Enabled: false
    Certificate: null
    PrivateKey: null
    ClientAuthRequired: true
    ClientRootCAs: [/var/hyperledger/orderer/tls/tlscacerts/ca.crt]
Metrics:
  Provider: prometheus
  Statsd:
    Network: udp
    Address: '127.0.0.1:8125'
    WriteInterval: 30s
    Prefix: null
Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
