global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  static_configs:
  - targets: ['localhost:9090']
- job_name: peer0.tex
  scrape_interval: 10s
  scheme: https
  static_configs:
  - targets: 
    - peer0.tex.domain.com:9450
  tls_config:
    ca_file: /etc/prometheus/tex.domain.com/tlsops/tlscacerts/ca.crt
    key_file: /etc/prometheus/tex.domain.com/tlsops/keystore/key.pem
    cert_file: /etc/prometheus/tex.domain.com/tlsops/signcerts/cert.pem
- job_name: peer0.lynkeus
  scrape_interval: 10s
  scheme: https
  tls_config:
    ca_file: /etc/prometheus/lynkeus.domain.com/tlsops/tlscacerts/ca.crt
    key_file: /etc/prometheus/lynkeus.domain.com/tlsops/keystore/key.pem
    cert_file: /etc/prometheus/lynkeus.domain.com/tlsops/signcerts/cert.pem
  static_configs:
  - targets: 
    - peer0.lynkeus.domain.com:9451
