{
 "title": "KRAKEN",
 "description": "HLF 2.2 Monitoring Dashboard.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Hyperledger Fabric Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Version",
   "type": "stat",
   "description": "The active version of Fabric.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fabric_version{instance=\"peer0.tex.dt4h.com:9450\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "singlestat",
   "description": "The active version of Go.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "go_info" }
   ]
  },
  {
   "title": "Ledger Block Height",
   "type": "stat",
   "description": "Height of the chain in blocks. ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ledger_blockchain_height" }
   ]
  },
  {
   "title": "Ledger Transaction Count",
   "type": "stat",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ledger_transaction_count\n" }
   ]
  },
  {
   "title": "Endorser Proposals Received/Accepted",
   "type": "stat",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "endorser_proposals_received" }
   ]
  },
  {
   "title": "Endorser Successful Proposals",
   "type": "stat",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "endorser_successful_proposals" }
   ]
  },
  {
   "title": "Couch DB Processing Time",
   "type": "graph",
   "description": "Time taken in seconds for the function to complete request to CouchDB.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(couchdb_processing_time_bucket[5m])) by (le))",
     "legendFormat": "CouchDB"
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Memory Allocations",
     "type": "graph",
     "description": "go_memstats_alloc_bytes",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Go Heap Objects",
     "type": "graph",
     "description": "go_memstats_alloc_bytes",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_heap_objects{job!=\"prometheus\"}[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Go Garbage Collection",
     "type": "graph",
     "description": "go_gc_duration_seconds",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds[5m])",
       "legendFormat": "{{instance}}/{{job}}"
      }
     ]
    },
    {
     "title": "Go Free Memory",
     "type": "graph",
     "description": "go_gc_duration_seconds",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total[5m])",
       "legendFormat": "{{instance}}/{{job}}"
      }
     ]
    }
   ]
  },
  { "title": "Ledger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Ledger Block Processing Time",
   "type": "graph",
   "description": "Time taken in seconds for ledger block processing.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_block_processing_time_bucket[5m])) by (le))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "StateDB Commit Time",
   "type": "graph",
   "description": "Time taken in seconds for committing block changes to state db.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ledger_statedb_commit_time_bucket[5m])) by (le))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Orderer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orderer Broadcasts",
     "type": "table-old",
     "description": "The number of transactions processed.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      { "expr": "broadcast_processed_count" }
     ]
    }
   ]
  },
  { "title": "Chaincode Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Chaincode Shim Requests",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(chaincode_shim_requests_received[5m])",
     "legendFormat": "{{channel}}, {{Received}}, {{chaincode}}, {{type}}"
    },
    {
     "expr": "rate(chaincode_shim_requests_completed[5m])",
     "legendFormat": "{{channel}}, {{Completed}},  {{chaincode}}, {{type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(chaincode_shim_request_duration_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Broadcast Enqueu",
   "type": "graph",
   "description": "broadcast_enqueue_duration_sum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{job!=\"prometheus\"}[5m])",
     "legendFormat": "{{channel}}, {{job}}"
    }
   ]
  },
  {
   "title": "gRPC Closed Connections",
   "type": "graph",
   "description": "rate(grpc_comm_conn_closed[5m])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_comm_conn_closed[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Chaincide shim requests",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "chaincode_shim_requests_received{chaincode!=\"_lifecycle.syscc\"}",
     "legendFormat": "{{Count}}, {{type}}"
    },
    {
     "expr": "chaincode_shim_requests_completed{chaincode!=\"_lifecycle.syscc\"}",
     "legendFormat": "{{Tota}}, {{type}}_RECEIVED"
    }
   ]
  }
 ]
}