#!/bin/bash


# This script renews the self signed tls-cert.pem that is generated by the server
# when the server is started. If this cert expires, the CA cannot accept commands.
# To renew, we have to delete it and restart the server and a new one is 
# generated automatically again. A new key is appended to msp/keystore

. configGlobals.sh
. util.sh

CAs="tlsca tlscaops"
chmod -R u+x  organizations/
chmod -R 755  organizations/


for ORG_NAME in $ORGS; do

	setParams "$ORG_NAME"
	echo ${FABRIC_CA_PATH}/$ORG_NAME
	[ ! -d ${FABRIC_CA_PATH}/$ORG_NAME ] && continue
	
	for ca in $CAs; do
		export FABRIC_CA_SERVER_HOME=$FABRIC_CA_PATH/${ORG_NAME}/fabric-${ca}-server-${ORG_NAME}
		OLDMSPSDIR=${FABRIC_CA_SERVER_HOME}/oldmsps
		# cp -r $FABRIC_CA_SERVER_HOME/oldmsps/keystore $FABRIC_CA_SERVER_HOME/msp

		[ ! -d "$OLDMSPSDIR" ] && mkdir -p "$OLDMSPSDIR"
		[ -d "$OLDMSPSDIR" ] && msp_no="$(ls "$OLDMSPSDIR" | wc -l)" && mkdir -p "$OLDMSPSDIR"/$msp_no/keystore
		mv $FABRIC_CA_SERVER_HOME/tls-cert.pem "$OLDMSPSDIR"/$msp_no
		mv $FABRIC_CA_SERVER_HOME/msp/keystore/tlskey.pem "$OLDMSPSDIR"/$msp_no/keystore/
		# sleep 2
		
		docker restart ${ca}_${ORG_NAME}
		sleep 1
		mv ${FABRIC_CA_SERVER_HOME}/msp/keystore/*sk ${FABRIC_CA_SERVER_HOME}/msp/keystore/tlskey.pem
	done
done

		# sudo rm -rf $FABRIC_CA_SERVER_HOME/msps $FABRIC_CA_SERVER_HOME/oldmsps


set -x
chmod -R u+x  organizations/ && chmod -R 755  organizations/

